#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DA_TOUR")]
	public partial class TourDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHITIET_DDC(CHITIET_DDC instance);
    partial void UpdateCHITIET_DDC(CHITIET_DDC instance);
    partial void DeleteCHITIET_DDC(CHITIET_DDC instance);
    partial void InsertCHUYEN(CHUYEN instance);
    partial void UpdateCHUYEN(CHUYEN instance);
    partial void DeleteCHUYEN(CHUYEN instance);
    partial void InsertCT_DIEMTHAMQUAN(CT_DIEMTHAMQUAN instance);
    partial void UpdateCT_DIEMTHAMQUAN(CT_DIEMTHAMQUAN instance);
    partial void DeleteCT_DIEMTHAMQUAN(CT_DIEMTHAMQUAN instance);
    partial void InsertDIEMDUNGCHAN(DIEMDUNGCHAN instance);
    partial void UpdateDIEMDUNGCHAN(DIEMDUNGCHAN instance);
    partial void DeleteDIEMDUNGCHAN(DIEMDUNGCHAN instance);
    partial void InsertDIEMTHAMQUAN(DIEMTHAMQUAN instance);
    partial void UpdateDIEMTHAMQUAN(DIEMTHAMQUAN instance);
    partial void DeleteDIEMTHAMQUAN(DIEMTHAMQUAN instance);
    partial void InsertDOAN(DOAN instance);
    partial void UpdateDOAN(DOAN instance);
    partial void DeleteDOAN(DOAN instance);
    partial void InsertHOPDONG(HOPDONG instance);
    partial void UpdateHOPDONG(HOPDONG instance);
    partial void DeleteHOPDONG(HOPDONG instance);
    partial void InsertHOPDONG_HDV(HOPDONG_HDV instance);
    partial void UpdateHOPDONG_HDV(HOPDONG_HDV instance);
    partial void DeleteHOPDONG_HDV(HOPDONG_HDV instance);
    partial void InsertHUONGDANVIEN(HUONGDANVIEN instance);
    partial void UpdateHUONGDANVIEN(HUONGDANVIEN instance);
    partial void DeleteHUONGDANVIEN(HUONGDANVIEN instance);
    partial void InsertLOTRINH(LOTRINH instance);
    partial void UpdateLOTRINH(LOTRINH instance);
    partial void DeleteLOTRINH(LOTRINH instance);
    partial void InsertLOTRINH_TOUR(LOTRINH_TOUR instance);
    partial void UpdateLOTRINH_TOUR(LOTRINH_TOUR instance);
    partial void DeleteLOTRINH_TOUR(LOTRINH_TOUR instance);
    partial void InsertNOIDEN(NOIDEN instance);
    partial void UpdateNOIDEN(NOIDEN instance);
    partial void DeleteNOIDEN(NOIDEN instance);
    partial void InsertNOIDI(NOIDI instance);
    partial void UpdateNOIDI(NOIDI instance);
    partial void DeleteNOIDI(NOIDI instance);
    partial void InsertPHIEUDANGKI(PHIEUDANGKI instance);
    partial void UpdatePHIEUDANGKI(PHIEUDANGKI instance);
    partial void DeletePHIEUDANGKI(PHIEUDANGKI instance);
    partial void InsertTOUR(TOUR instance);
    partial void UpdateTOUR(TOUR instance);
    partial void DeleteTOUR(TOUR instance);
    #endregion
		
		public TourDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DA_TOURConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TourDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TourDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TourDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TourDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHITIET_DDC> CHITIET_DDCs
		{
			get
			{
				return this.GetTable<CHITIET_DDC>();
			}
		}
		
		public System.Data.Linq.Table<CHUYEN> CHUYENs
		{
			get
			{
				return this.GetTable<CHUYEN>();
			}
		}
		
		public System.Data.Linq.Table<CT_DIEMTHAMQUAN> CT_DIEMTHAMQUANs
		{
			get
			{
				return this.GetTable<CT_DIEMTHAMQUAN>();
			}
		}
		
		public System.Data.Linq.Table<DIEMDUNGCHAN> DIEMDUNGCHANs
		{
			get
			{
				return this.GetTable<DIEMDUNGCHAN>();
			}
		}
		
		public System.Data.Linq.Table<DIEMTHAMQUAN> DIEMTHAMQUANs
		{
			get
			{
				return this.GetTable<DIEMTHAMQUAN>();
			}
		}
		
		public System.Data.Linq.Table<DOAN> DOANs
		{
			get
			{
				return this.GetTable<DOAN>();
			}
		}
		
		public System.Data.Linq.Table<HOPDONG> HOPDONGs
		{
			get
			{
				return this.GetTable<HOPDONG>();
			}
		}
		
		public System.Data.Linq.Table<HOPDONG_HDV> HOPDONG_HDVs
		{
			get
			{
				return this.GetTable<HOPDONG_HDV>();
			}
		}
		
		public System.Data.Linq.Table<HUONGDANVIEN> HUONGDANVIENs
		{
			get
			{
				return this.GetTable<HUONGDANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<LOTRINH> LOTRINHs
		{
			get
			{
				return this.GetTable<LOTRINH>();
			}
		}
		
		public System.Data.Linq.Table<LOTRINH_TOUR> LOTRINH_TOURs
		{
			get
			{
				return this.GetTable<LOTRINH_TOUR>();
			}
		}
		
		public System.Data.Linq.Table<NOIDEN> NOIDENs
		{
			get
			{
				return this.GetTable<NOIDEN>();
			}
		}
		
		public System.Data.Linq.Table<NOIDI> NOIDIs
		{
			get
			{
				return this.GetTable<NOIDI>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUDANGKI> PHIEUDANGKIs
		{
			get
			{
				return this.GetTable<PHIEUDANGKI>();
			}
		}
		
		public System.Data.Linq.Table<TOUR> TOURs
		{
			get
			{
				return this.GetTable<TOUR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIET_DDC")]
	public partial class CHITIET_DDC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANOIDI;
		
		private string _MANOIDEN;
		
		private string _MA_DDC;
		
		private System.Nullable<int> _THOIGIANDC;
		
		private EntityRef<DIEMDUNGCHAN> _DIEMDUNGCHAN;
		
		private EntityRef<LOTRINH> _LOTRINH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANOIDIChanging(string value);
    partial void OnMANOIDIChanged();
    partial void OnMANOIDENChanging(string value);
    partial void OnMANOIDENChanged();
    partial void OnMA_DDCChanging(string value);
    partial void OnMA_DDCChanged();
    partial void OnTHOIGIANDCChanging(System.Nullable<int> value);
    partial void OnTHOIGIANDCChanged();
    #endregion
		
		public CHITIET_DDC()
		{
			this._DIEMDUNGCHAN = default(EntityRef<DIEMDUNGCHAN>);
			this._LOTRINH = default(EntityRef<LOTRINH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANOIDI", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANOIDI
		{
			get
			{
				return this._MANOIDI;
			}
			set
			{
				if ((this._MANOIDI != value))
				{
					if (this._LOTRINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANOIDIChanging(value);
					this.SendPropertyChanging();
					this._MANOIDI = value;
					this.SendPropertyChanged("MANOIDI");
					this.OnMANOIDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANOIDEN", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANOIDEN
		{
			get
			{
				return this._MANOIDEN;
			}
			set
			{
				if ((this._MANOIDEN != value))
				{
					if (this._LOTRINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANOIDENChanging(value);
					this.SendPropertyChanging();
					this._MANOIDEN = value;
					this.SendPropertyChanged("MANOIDEN");
					this.OnMANOIDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DDC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_DDC
		{
			get
			{
				return this._MA_DDC;
			}
			set
			{
				if ((this._MA_DDC != value))
				{
					if (this._DIEMDUNGCHAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_DDCChanging(value);
					this.SendPropertyChanging();
					this._MA_DDC = value;
					this.SendPropertyChanged("MA_DDC");
					this.OnMA_DDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANDC", DbType="Int")]
		public System.Nullable<int> THOIGIANDC
		{
			get
			{
				return this._THOIGIANDC;
			}
			set
			{
				if ((this._THOIGIANDC != value))
				{
					this.OnTHOIGIANDCChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANDC = value;
					this.SendPropertyChanged("THOIGIANDC");
					this.OnTHOIGIANDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIEMDUNGCHAN_CHITIET_DDC", Storage="_DIEMDUNGCHAN", ThisKey="MA_DDC", OtherKey="MA_DDC", IsForeignKey=true)]
		public DIEMDUNGCHAN DIEMDUNGCHAN
		{
			get
			{
				return this._DIEMDUNGCHAN.Entity;
			}
			set
			{
				DIEMDUNGCHAN previousValue = this._DIEMDUNGCHAN.Entity;
				if (((previousValue != value) 
							|| (this._DIEMDUNGCHAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIEMDUNGCHAN.Entity = null;
						previousValue.CHITIET_DDCs.Remove(this);
					}
					this._DIEMDUNGCHAN.Entity = value;
					if ((value != null))
					{
						value.CHITIET_DDCs.Add(this);
						this._MA_DDC = value.MA_DDC;
					}
					else
					{
						this._MA_DDC = default(string);
					}
					this.SendPropertyChanged("DIEMDUNGCHAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOTRINH_CHITIET_DDC", Storage="_LOTRINH", ThisKey="MANOIDI,MANOIDEN", OtherKey="MANOIDI,MANOIDEN", IsForeignKey=true)]
		public LOTRINH LOTRINH
		{
			get
			{
				return this._LOTRINH.Entity;
			}
			set
			{
				LOTRINH previousValue = this._LOTRINH.Entity;
				if (((previousValue != value) 
							|| (this._LOTRINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOTRINH.Entity = null;
						previousValue.CHITIET_DDCs.Remove(this);
					}
					this._LOTRINH.Entity = value;
					if ((value != null))
					{
						value.CHITIET_DDCs.Add(this);
						this._MANOIDI = value.MANOIDI;
						this._MANOIDEN = value.MANOIDEN;
					}
					else
					{
						this._MANOIDI = default(string);
						this._MANOIDEN = default(string);
					}
					this.SendPropertyChanged("LOTRINH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUYEN")]
	public partial class CHUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACHUYEN;
		
		private string _TENCHUYEN;
		
		private System.Nullable<System.DateTime> _NGAYDI;
		
		private string _MA_HDV;
		
		private string _MAPHIEU;
		
		private string _MATOUR;
		
		private EntityRef<HUONGDANVIEN> _HUONGDANVIEN;
		
		private EntityRef<PHIEUDANGKI> _PHIEUDANGKI;
		
		private EntityRef<TOUR> _TOUR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACHUYENChanging(string value);
    partial void OnMACHUYENChanged();
    partial void OnTENCHUYENChanging(string value);
    partial void OnTENCHUYENChanged();
    partial void OnNGAYDIChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYDIChanged();
    partial void OnMA_HDVChanging(string value);
    partial void OnMA_HDVChanged();
    partial void OnMAPHIEUChanging(string value);
    partial void OnMAPHIEUChanged();
    partial void OnMATOURChanging(string value);
    partial void OnMATOURChanged();
    #endregion
		
		public CHUYEN()
		{
			this._HUONGDANVIEN = default(EntityRef<HUONGDANVIEN>);
			this._PHIEUDANGKI = default(EntityRef<PHIEUDANGKI>);
			this._TOUR = default(EntityRef<TOUR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUYEN", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACHUYEN
		{
			get
			{
				return this._MACHUYEN;
			}
			set
			{
				if ((this._MACHUYEN != value))
				{
					this.OnMACHUYENChanging(value);
					this.SendPropertyChanging();
					this._MACHUYEN = value;
					this.SendPropertyChanged("MACHUYEN");
					this.OnMACHUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCHUYEN", DbType="NVarChar(50)")]
		public string TENCHUYEN
		{
			get
			{
				return this._TENCHUYEN;
			}
			set
			{
				if ((this._TENCHUYEN != value))
				{
					this.OnTENCHUYENChanging(value);
					this.SendPropertyChanging();
					this._TENCHUYEN = value;
					this.SendPropertyChanged("TENCHUYEN");
					this.OnTENCHUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDI", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYDI
		{
			get
			{
				return this._NGAYDI;
			}
			set
			{
				if ((this._NGAYDI != value))
				{
					this.OnNGAYDIChanging(value);
					this.SendPropertyChanging();
					this._NGAYDI = value;
					this.SendPropertyChanged("NGAYDI");
					this.OnNGAYDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_HDV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_HDV
		{
			get
			{
				return this._MA_HDV;
			}
			set
			{
				if ((this._MA_HDV != value))
				{
					if (this._HUONGDANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_HDVChanging(value);
					this.SendPropertyChanging();
					this._MA_HDV = value;
					this.SendPropertyChanged("MA_HDV");
					this.OnMA_HDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEU", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MAPHIEU
		{
			get
			{
				return this._MAPHIEU;
			}
			set
			{
				if ((this._MAPHIEU != value))
				{
					if (this._PHIEUDANGKI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHIEUChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEU = value;
					this.SendPropertyChanged("MAPHIEU");
					this.OnMAPHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATOUR", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MATOUR
		{
			get
			{
				return this._MATOUR;
			}
			set
			{
				if ((this._MATOUR != value))
				{
					if (this._TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATOURChanging(value);
					this.SendPropertyChanging();
					this._MATOUR = value;
					this.SendPropertyChanged("MATOUR");
					this.OnMATOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HUONGDANVIEN_CHUYEN", Storage="_HUONGDANVIEN", ThisKey="MA_HDV", OtherKey="MA_HDV", IsForeignKey=true)]
		public HUONGDANVIEN HUONGDANVIEN
		{
			get
			{
				return this._HUONGDANVIEN.Entity;
			}
			set
			{
				HUONGDANVIEN previousValue = this._HUONGDANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._HUONGDANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HUONGDANVIEN.Entity = null;
						previousValue.CHUYENs.Remove(this);
					}
					this._HUONGDANVIEN.Entity = value;
					if ((value != null))
					{
						value.CHUYENs.Add(this);
						this._MA_HDV = value.MA_HDV;
					}
					else
					{
						this._MA_HDV = default(string);
					}
					this.SendPropertyChanged("HUONGDANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDANGKI_CHUYEN", Storage="_PHIEUDANGKI", ThisKey="MAPHIEU", OtherKey="MAPHIEU", IsForeignKey=true)]
		public PHIEUDANGKI PHIEUDANGKI
		{
			get
			{
				return this._PHIEUDANGKI.Entity;
			}
			set
			{
				PHIEUDANGKI previousValue = this._PHIEUDANGKI.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUDANGKI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUDANGKI.Entity = null;
						previousValue.CHUYENs.Remove(this);
					}
					this._PHIEUDANGKI.Entity = value;
					if ((value != null))
					{
						value.CHUYENs.Add(this);
						this._MAPHIEU = value.MAPHIEU;
					}
					else
					{
						this._MAPHIEU = default(string);
					}
					this.SendPropertyChanged("PHIEUDANGKI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_CHUYEN", Storage="_TOUR", ThisKey="MATOUR", OtherKey="MATOUR", IsForeignKey=true)]
		public TOUR TOUR
		{
			get
			{
				return this._TOUR.Entity;
			}
			set
			{
				TOUR previousValue = this._TOUR.Entity;
				if (((previousValue != value) 
							|| (this._TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOUR.Entity = null;
						previousValue.CHUYENs.Remove(this);
					}
					this._TOUR.Entity = value;
					if ((value != null))
					{
						value.CHUYENs.Add(this);
						this._MATOUR = value.MATOUR;
					}
					else
					{
						this._MATOUR = default(string);
					}
					this.SendPropertyChanged("TOUR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_DIEMTHAMQUAN")]
	public partial class CT_DIEMTHAMQUAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATOUR;
		
		private string _MA_DTQ;
		
		private System.Nullable<int> _THOIGIAN_TQ;
		
		private EntityRef<DIEMTHAMQUAN> _DIEMTHAMQUAN;
		
		private EntityRef<TOUR> _TOUR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATOURChanging(string value);
    partial void OnMATOURChanged();
    partial void OnMA_DTQChanging(string value);
    partial void OnMA_DTQChanged();
    partial void OnTHOIGIAN_TQChanging(System.Nullable<int> value);
    partial void OnTHOIGIAN_TQChanged();
    #endregion
		
		public CT_DIEMTHAMQUAN()
		{
			this._DIEMTHAMQUAN = default(EntityRef<DIEMTHAMQUAN>);
			this._TOUR = default(EntityRef<TOUR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATOUR", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATOUR
		{
			get
			{
				return this._MATOUR;
			}
			set
			{
				if ((this._MATOUR != value))
				{
					if (this._TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATOURChanging(value);
					this.SendPropertyChanging();
					this._MATOUR = value;
					this.SendPropertyChanged("MATOUR");
					this.OnMATOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DTQ", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_DTQ
		{
			get
			{
				return this._MA_DTQ;
			}
			set
			{
				if ((this._MA_DTQ != value))
				{
					if (this._DIEMTHAMQUAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_DTQChanging(value);
					this.SendPropertyChanging();
					this._MA_DTQ = value;
					this.SendPropertyChanged("MA_DTQ");
					this.OnMA_DTQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIAN_TQ", DbType="Int")]
		public System.Nullable<int> THOIGIAN_TQ
		{
			get
			{
				return this._THOIGIAN_TQ;
			}
			set
			{
				if ((this._THOIGIAN_TQ != value))
				{
					this.OnTHOIGIAN_TQChanging(value);
					this.SendPropertyChanging();
					this._THOIGIAN_TQ = value;
					this.SendPropertyChanged("THOIGIAN_TQ");
					this.OnTHOIGIAN_TQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIEMTHAMQUAN_CT_DIEMTHAMQUAN", Storage="_DIEMTHAMQUAN", ThisKey="MA_DTQ", OtherKey="MA_DTQ", IsForeignKey=true)]
		public DIEMTHAMQUAN DIEMTHAMQUAN
		{
			get
			{
				return this._DIEMTHAMQUAN.Entity;
			}
			set
			{
				DIEMTHAMQUAN previousValue = this._DIEMTHAMQUAN.Entity;
				if (((previousValue != value) 
							|| (this._DIEMTHAMQUAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIEMTHAMQUAN.Entity = null;
						previousValue.CT_DIEMTHAMQUANs.Remove(this);
					}
					this._DIEMTHAMQUAN.Entity = value;
					if ((value != null))
					{
						value.CT_DIEMTHAMQUANs.Add(this);
						this._MA_DTQ = value.MA_DTQ;
					}
					else
					{
						this._MA_DTQ = default(string);
					}
					this.SendPropertyChanged("DIEMTHAMQUAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_CT_DIEMTHAMQUAN", Storage="_TOUR", ThisKey="MATOUR", OtherKey="MATOUR", IsForeignKey=true)]
		public TOUR TOUR
		{
			get
			{
				return this._TOUR.Entity;
			}
			set
			{
				TOUR previousValue = this._TOUR.Entity;
				if (((previousValue != value) 
							|| (this._TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOUR.Entity = null;
						previousValue.CT_DIEMTHAMQUANs.Remove(this);
					}
					this._TOUR.Entity = value;
					if ((value != null))
					{
						value.CT_DIEMTHAMQUANs.Add(this);
						this._MATOUR = value.MATOUR;
					}
					else
					{
						this._MATOUR = default(string);
					}
					this.SendPropertyChanged("TOUR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIEMDUNGCHAN")]
	public partial class DIEMDUNGCHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_DDC;
		
		private string _TEN_DDC;
		
		private string _THANHPHO;
		
		private EntitySet<CHITIET_DDC> _CHITIET_DDCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_DDCChanging(string value);
    partial void OnMA_DDCChanged();
    partial void OnTEN_DDCChanging(string value);
    partial void OnTEN_DDCChanged();
    partial void OnTHANHPHOChanging(string value);
    partial void OnTHANHPHOChanged();
    #endregion
		
		public DIEMDUNGCHAN()
		{
			this._CHITIET_DDCs = new EntitySet<CHITIET_DDC>(new Action<CHITIET_DDC>(this.attach_CHITIET_DDCs), new Action<CHITIET_DDC>(this.detach_CHITIET_DDCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DDC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_DDC
		{
			get
			{
				return this._MA_DDC;
			}
			set
			{
				if ((this._MA_DDC != value))
				{
					this.OnMA_DDCChanging(value);
					this.SendPropertyChanging();
					this._MA_DDC = value;
					this.SendPropertyChanged("MA_DDC");
					this.OnMA_DDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_DDC", DbType="NVarChar(50)")]
		public string TEN_DDC
		{
			get
			{
				return this._TEN_DDC;
			}
			set
			{
				if ((this._TEN_DDC != value))
				{
					this.OnTEN_DDCChanging(value);
					this.SendPropertyChanging();
					this._TEN_DDC = value;
					this.SendPropertyChanged("TEN_DDC");
					this.OnTEN_DDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHPHO", DbType="NVarChar(50)")]
		public string THANHPHO
		{
			get
			{
				return this._THANHPHO;
			}
			set
			{
				if ((this._THANHPHO != value))
				{
					this.OnTHANHPHOChanging(value);
					this.SendPropertyChanging();
					this._THANHPHO = value;
					this.SendPropertyChanged("THANHPHO");
					this.OnTHANHPHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIEMDUNGCHAN_CHITIET_DDC", Storage="_CHITIET_DDCs", ThisKey="MA_DDC", OtherKey="MA_DDC")]
		public EntitySet<CHITIET_DDC> CHITIET_DDCs
		{
			get
			{
				return this._CHITIET_DDCs;
			}
			set
			{
				this._CHITIET_DDCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIET_DDCs(CHITIET_DDC entity)
		{
			this.SendPropertyChanging();
			entity.DIEMDUNGCHAN = this;
		}
		
		private void detach_CHITIET_DDCs(CHITIET_DDC entity)
		{
			this.SendPropertyChanging();
			entity.DIEMDUNGCHAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIEMTHAMQUAN")]
	public partial class DIEMTHAMQUAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_DTQ;
		
		private string _TEN_DTQ;
		
		private string _DIADIEMTHAMQUAN;
		
		private string _NOIDUNG_TQ;
		
		private string _YNGHIA_DTQ;
		
		private EntitySet<CT_DIEMTHAMQUAN> _CT_DIEMTHAMQUANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_DTQChanging(string value);
    partial void OnMA_DTQChanged();
    partial void OnTEN_DTQChanging(string value);
    partial void OnTEN_DTQChanged();
    partial void OnDIADIEMTHAMQUANChanging(string value);
    partial void OnDIADIEMTHAMQUANChanged();
    partial void OnNOIDUNG_TQChanging(string value);
    partial void OnNOIDUNG_TQChanged();
    partial void OnYNGHIA_DTQChanging(string value);
    partial void OnYNGHIA_DTQChanged();
    #endregion
		
		public DIEMTHAMQUAN()
		{
			this._CT_DIEMTHAMQUANs = new EntitySet<CT_DIEMTHAMQUAN>(new Action<CT_DIEMTHAMQUAN>(this.attach_CT_DIEMTHAMQUANs), new Action<CT_DIEMTHAMQUAN>(this.detach_CT_DIEMTHAMQUANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DTQ", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_DTQ
		{
			get
			{
				return this._MA_DTQ;
			}
			set
			{
				if ((this._MA_DTQ != value))
				{
					this.OnMA_DTQChanging(value);
					this.SendPropertyChanging();
					this._MA_DTQ = value;
					this.SendPropertyChanged("MA_DTQ");
					this.OnMA_DTQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_DTQ", DbType="NVarChar(50)")]
		public string TEN_DTQ
		{
			get
			{
				return this._TEN_DTQ;
			}
			set
			{
				if ((this._TEN_DTQ != value))
				{
					this.OnTEN_DTQChanging(value);
					this.SendPropertyChanging();
					this._TEN_DTQ = value;
					this.SendPropertyChanged("TEN_DTQ");
					this.OnTEN_DTQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIADIEMTHAMQUAN", DbType="NVarChar(50)")]
		public string DIADIEMTHAMQUAN
		{
			get
			{
				return this._DIADIEMTHAMQUAN;
			}
			set
			{
				if ((this._DIADIEMTHAMQUAN != value))
				{
					this.OnDIADIEMTHAMQUANChanging(value);
					this.SendPropertyChanging();
					this._DIADIEMTHAMQUAN = value;
					this.SendPropertyChanged("DIADIEMTHAMQUAN");
					this.OnDIADIEMTHAMQUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG_TQ", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string NOIDUNG_TQ
		{
			get
			{
				return this._NOIDUNG_TQ;
			}
			set
			{
				if ((this._NOIDUNG_TQ != value))
				{
					this.OnNOIDUNG_TQChanging(value);
					this.SendPropertyChanging();
					this._NOIDUNG_TQ = value;
					this.SendPropertyChanged("NOIDUNG_TQ");
					this.OnNOIDUNG_TQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YNGHIA_DTQ", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string YNGHIA_DTQ
		{
			get
			{
				return this._YNGHIA_DTQ;
			}
			set
			{
				if ((this._YNGHIA_DTQ != value))
				{
					this.OnYNGHIA_DTQChanging(value);
					this.SendPropertyChanging();
					this._YNGHIA_DTQ = value;
					this.SendPropertyChanged("YNGHIA_DTQ");
					this.OnYNGHIA_DTQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIEMTHAMQUAN_CT_DIEMTHAMQUAN", Storage="_CT_DIEMTHAMQUANs", ThisKey="MA_DTQ", OtherKey="MA_DTQ")]
		public EntitySet<CT_DIEMTHAMQUAN> CT_DIEMTHAMQUANs
		{
			get
			{
				return this._CT_DIEMTHAMQUANs;
			}
			set
			{
				this._CT_DIEMTHAMQUANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_DIEMTHAMQUANs(CT_DIEMTHAMQUAN entity)
		{
			this.SendPropertyChanging();
			entity.DIEMTHAMQUAN = this;
		}
		
		private void detach_CT_DIEMTHAMQUANs(CT_DIEMTHAMQUAN entity)
		{
			this.SendPropertyChanging();
			entity.DIEMTHAMQUAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOAN")]
	public partial class DOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADOAN;
		
		private string _TEN_TRUONGDOAN;
		
		private string _DIACHI;
		
		private System.Nullable<int> _SDT;
		
		private System.Nullable<int> _SONGUOIDI;
		
		private EntitySet<HOPDONG> _HOPDONGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADOANChanging(string value);
    partial void OnMADOANChanged();
    partial void OnTEN_TRUONGDOANChanging(string value);
    partial void OnTEN_TRUONGDOANChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnSDTChanging(System.Nullable<int> value);
    partial void OnSDTChanged();
    partial void OnSONGUOIDIChanging(System.Nullable<int> value);
    partial void OnSONGUOIDIChanged();
    #endregion
		
		public DOAN()
		{
			this._HOPDONGs = new EntitySet<HOPDONG>(new Action<HOPDONG>(this.attach_HOPDONGs), new Action<HOPDONG>(this.detach_HOPDONGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADOAN", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADOAN
		{
			get
			{
				return this._MADOAN;
			}
			set
			{
				if ((this._MADOAN != value))
				{
					this.OnMADOANChanging(value);
					this.SendPropertyChanging();
					this._MADOAN = value;
					this.SendPropertyChanged("MADOAN");
					this.OnMADOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_TRUONGDOAN", DbType="NVarChar(50)")]
		public string TEN_TRUONGDOAN
		{
			get
			{
				return this._TEN_TRUONGDOAN;
			}
			set
			{
				if ((this._TEN_TRUONGDOAN != value))
				{
					this.OnTEN_TRUONGDOANChanging(value);
					this.SendPropertyChanging();
					this._TEN_TRUONGDOAN = value;
					this.SendPropertyChanged("TEN_TRUONGDOAN");
					this.OnTEN_TRUONGDOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int")]
		public System.Nullable<int> SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONGUOIDI", DbType="Int")]
		public System.Nullable<int> SONGUOIDI
		{
			get
			{
				return this._SONGUOIDI;
			}
			set
			{
				if ((this._SONGUOIDI != value))
				{
					this.OnSONGUOIDIChanging(value);
					this.SendPropertyChanging();
					this._SONGUOIDI = value;
					this.SendPropertyChanged("SONGUOIDI");
					this.OnSONGUOIDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOAN_HOPDONG", Storage="_HOPDONGs", ThisKey="MADOAN", OtherKey="MADOAN")]
		public EntitySet<HOPDONG> HOPDONGs
		{
			get
			{
				return this._HOPDONGs;
			}
			set
			{
				this._HOPDONGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.DOAN = this;
		}
		
		private void detach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.DOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOPDONG")]
	public partial class HOPDONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_HD;
		
		private System.Nullable<System.DateTime> _NGAYLAP_HD;
		
		private System.Nullable<int> _SONGAYDI;
		
		private string _NOIDUNG_HD;
		
		private System.Nullable<int> _SONGUOIDI;
		
		private string _DIADIEMDEN;
		
		private System.Nullable<System.DateTime> _NGAYDI_HD;
		
		private string _MADOAN;
		
		private string _MATOUR;
		
		private EntitySet<HOPDONG_HDV> _HOPDONG_HDVs;
		
		private EntityRef<DOAN> _DOAN;
		
		private EntityRef<TOUR> _TOUR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_HDChanging(string value);
    partial void OnMA_HDChanged();
    partial void OnNGAYLAP_HDChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAP_HDChanged();
    partial void OnSONGAYDIChanging(System.Nullable<int> value);
    partial void OnSONGAYDIChanged();
    partial void OnNOIDUNG_HDChanging(string value);
    partial void OnNOIDUNG_HDChanged();
    partial void OnSONGUOIDIChanging(System.Nullable<int> value);
    partial void OnSONGUOIDIChanged();
    partial void OnDIADIEMDENChanging(string value);
    partial void OnDIADIEMDENChanged();
    partial void OnNGAYDI_HDChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYDI_HDChanged();
    partial void OnMADOANChanging(string value);
    partial void OnMADOANChanged();
    partial void OnMATOURChanging(string value);
    partial void OnMATOURChanged();
    #endregion
		
		public HOPDONG()
		{
			this._HOPDONG_HDVs = new EntitySet<HOPDONG_HDV>(new Action<HOPDONG_HDV>(this.attach_HOPDONG_HDVs), new Action<HOPDONG_HDV>(this.detach_HOPDONG_HDVs));
			this._DOAN = default(EntityRef<DOAN>);
			this._TOUR = default(EntityRef<TOUR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_HD", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_HD
		{
			get
			{
				return this._MA_HD;
			}
			set
			{
				if ((this._MA_HD != value))
				{
					this.OnMA_HDChanging(value);
					this.SendPropertyChanging();
					this._MA_HD = value;
					this.SendPropertyChanged("MA_HD");
					this.OnMA_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP_HD", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYLAP_HD
		{
			get
			{
				return this._NGAYLAP_HD;
			}
			set
			{
				if ((this._NGAYLAP_HD != value))
				{
					this.OnNGAYLAP_HDChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP_HD = value;
					this.SendPropertyChanged("NGAYLAP_HD");
					this.OnNGAYLAP_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONGAYDI", DbType="Int")]
		public System.Nullable<int> SONGAYDI
		{
			get
			{
				return this._SONGAYDI;
			}
			set
			{
				if ((this._SONGAYDI != value))
				{
					this.OnSONGAYDIChanging(value);
					this.SendPropertyChanging();
					this._SONGAYDI = value;
					this.SendPropertyChanged("SONGAYDI");
					this.OnSONGAYDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG_HD", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string NOIDUNG_HD
		{
			get
			{
				return this._NOIDUNG_HD;
			}
			set
			{
				if ((this._NOIDUNG_HD != value))
				{
					this.OnNOIDUNG_HDChanging(value);
					this.SendPropertyChanging();
					this._NOIDUNG_HD = value;
					this.SendPropertyChanged("NOIDUNG_HD");
					this.OnNOIDUNG_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONGUOIDI", DbType="Int")]
		public System.Nullable<int> SONGUOIDI
		{
			get
			{
				return this._SONGUOIDI;
			}
			set
			{
				if ((this._SONGUOIDI != value))
				{
					this.OnSONGUOIDIChanging(value);
					this.SendPropertyChanging();
					this._SONGUOIDI = value;
					this.SendPropertyChanged("SONGUOIDI");
					this.OnSONGUOIDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIADIEMDEN", DbType="NVarChar(50)")]
		public string DIADIEMDEN
		{
			get
			{
				return this._DIADIEMDEN;
			}
			set
			{
				if ((this._DIADIEMDEN != value))
				{
					this.OnDIADIEMDENChanging(value);
					this.SendPropertyChanging();
					this._DIADIEMDEN = value;
					this.SendPropertyChanged("DIADIEMDEN");
					this.OnDIADIEMDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDI_HD", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYDI_HD
		{
			get
			{
				return this._NGAYDI_HD;
			}
			set
			{
				if ((this._NGAYDI_HD != value))
				{
					this.OnNGAYDI_HDChanging(value);
					this.SendPropertyChanging();
					this._NGAYDI_HD = value;
					this.SendPropertyChanged("NGAYDI_HD");
					this.OnNGAYDI_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADOAN", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MADOAN
		{
			get
			{
				return this._MADOAN;
			}
			set
			{
				if ((this._MADOAN != value))
				{
					if (this._DOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADOANChanging(value);
					this.SendPropertyChanging();
					this._MADOAN = value;
					this.SendPropertyChanged("MADOAN");
					this.OnMADOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATOUR", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MATOUR
		{
			get
			{
				return this._MATOUR;
			}
			set
			{
				if ((this._MATOUR != value))
				{
					if (this._TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATOURChanging(value);
					this.SendPropertyChanging();
					this._MATOUR = value;
					this.SendPropertyChanged("MATOUR");
					this.OnMATOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOPDONG_HOPDONG_HDV", Storage="_HOPDONG_HDVs", ThisKey="MA_HD", OtherKey="MA_HD")]
		public EntitySet<HOPDONG_HDV> HOPDONG_HDVs
		{
			get
			{
				return this._HOPDONG_HDVs;
			}
			set
			{
				this._HOPDONG_HDVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOAN_HOPDONG", Storage="_DOAN", ThisKey="MADOAN", OtherKey="MADOAN", IsForeignKey=true)]
		public DOAN DOAN
		{
			get
			{
				return this._DOAN.Entity;
			}
			set
			{
				DOAN previousValue = this._DOAN.Entity;
				if (((previousValue != value) 
							|| (this._DOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOAN.Entity = null;
						previousValue.HOPDONGs.Remove(this);
					}
					this._DOAN.Entity = value;
					if ((value != null))
					{
						value.HOPDONGs.Add(this);
						this._MADOAN = value.MADOAN;
					}
					else
					{
						this._MADOAN = default(string);
					}
					this.SendPropertyChanged("DOAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_HOPDONG", Storage="_TOUR", ThisKey="MATOUR", OtherKey="MATOUR", IsForeignKey=true)]
		public TOUR TOUR
		{
			get
			{
				return this._TOUR.Entity;
			}
			set
			{
				TOUR previousValue = this._TOUR.Entity;
				if (((previousValue != value) 
							|| (this._TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOUR.Entity = null;
						previousValue.HOPDONGs.Remove(this);
					}
					this._TOUR.Entity = value;
					if ((value != null))
					{
						value.HOPDONGs.Add(this);
						this._MATOUR = value.MATOUR;
					}
					else
					{
						this._MATOUR = default(string);
					}
					this.SendPropertyChanged("TOUR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOPDONG_HDVs(HOPDONG_HDV entity)
		{
			this.SendPropertyChanging();
			entity.HOPDONG = this;
		}
		
		private void detach_HOPDONG_HDVs(HOPDONG_HDV entity)
		{
			this.SendPropertyChanging();
			entity.HOPDONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOPDONG_HDV")]
	public partial class HOPDONG_HDV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_HD;
		
		private string _MA_HDV;
		
		private string _NOIDUNG_HD;
		
		private System.Nullable<decimal> _LUONGCB;
		
		private EntityRef<HOPDONG> _HOPDONG;
		
		private EntityRef<HUONGDANVIEN> _HUONGDANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_HDChanging(string value);
    partial void OnMA_HDChanged();
    partial void OnMA_HDVChanging(string value);
    partial void OnMA_HDVChanged();
    partial void OnNOIDUNG_HDChanging(string value);
    partial void OnNOIDUNG_HDChanged();
    partial void OnLUONGCBChanging(System.Nullable<decimal> value);
    partial void OnLUONGCBChanged();
    #endregion
		
		public HOPDONG_HDV()
		{
			this._HOPDONG = default(EntityRef<HOPDONG>);
			this._HUONGDANVIEN = default(EntityRef<HUONGDANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_HD", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_HD
		{
			get
			{
				return this._MA_HD;
			}
			set
			{
				if ((this._MA_HD != value))
				{
					if (this._HOPDONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_HDChanging(value);
					this.SendPropertyChanging();
					this._MA_HD = value;
					this.SendPropertyChanged("MA_HD");
					this.OnMA_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_HDV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_HDV
		{
			get
			{
				return this._MA_HDV;
			}
			set
			{
				if ((this._MA_HDV != value))
				{
					if (this._HUONGDANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_HDVChanging(value);
					this.SendPropertyChanging();
					this._MA_HDV = value;
					this.SendPropertyChanged("MA_HDV");
					this.OnMA_HDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG_HD", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string NOIDUNG_HD
		{
			get
			{
				return this._NOIDUNG_HD;
			}
			set
			{
				if ((this._NOIDUNG_HD != value))
				{
					this.OnNOIDUNG_HDChanging(value);
					this.SendPropertyChanging();
					this._NOIDUNG_HD = value;
					this.SendPropertyChanged("NOIDUNG_HD");
					this.OnNOIDUNG_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUONGCB", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> LUONGCB
		{
			get
			{
				return this._LUONGCB;
			}
			set
			{
				if ((this._LUONGCB != value))
				{
					this.OnLUONGCBChanging(value);
					this.SendPropertyChanging();
					this._LUONGCB = value;
					this.SendPropertyChanged("LUONGCB");
					this.OnLUONGCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOPDONG_HOPDONG_HDV", Storage="_HOPDONG", ThisKey="MA_HD", OtherKey="MA_HD", IsForeignKey=true)]
		public HOPDONG HOPDONG
		{
			get
			{
				return this._HOPDONG.Entity;
			}
			set
			{
				HOPDONG previousValue = this._HOPDONG.Entity;
				if (((previousValue != value) 
							|| (this._HOPDONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOPDONG.Entity = null;
						previousValue.HOPDONG_HDVs.Remove(this);
					}
					this._HOPDONG.Entity = value;
					if ((value != null))
					{
						value.HOPDONG_HDVs.Add(this);
						this._MA_HD = value.MA_HD;
					}
					else
					{
						this._MA_HD = default(string);
					}
					this.SendPropertyChanged("HOPDONG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HUONGDANVIEN_HOPDONG_HDV", Storage="_HUONGDANVIEN", ThisKey="MA_HDV", OtherKey="MA_HDV", IsForeignKey=true)]
		public HUONGDANVIEN HUONGDANVIEN
		{
			get
			{
				return this._HUONGDANVIEN.Entity;
			}
			set
			{
				HUONGDANVIEN previousValue = this._HUONGDANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._HUONGDANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HUONGDANVIEN.Entity = null;
						previousValue.HOPDONG_HDVs.Remove(this);
					}
					this._HUONGDANVIEN.Entity = value;
					if ((value != null))
					{
						value.HOPDONG_HDVs.Add(this);
						this._MA_HDV = value.MA_HDV;
					}
					else
					{
						this._MA_HDV = default(string);
					}
					this.SendPropertyChanged("HUONGDANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HUONGDANVIEN")]
	public partial class HUONGDANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_HDV;
		
		private string _TEN_HDV;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private System.Nullable<int> _SDT;
		
		private EntitySet<CHUYEN> _CHUYENs;
		
		private EntitySet<HOPDONG_HDV> _HOPDONG_HDVs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_HDVChanging(string value);
    partial void OnMA_HDVChanged();
    partial void OnTEN_HDVChanging(string value);
    partial void OnTEN_HDVChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnSDTChanging(System.Nullable<int> value);
    partial void OnSDTChanged();
    #endregion
		
		public HUONGDANVIEN()
		{
			this._CHUYENs = new EntitySet<CHUYEN>(new Action<CHUYEN>(this.attach_CHUYENs), new Action<CHUYEN>(this.detach_CHUYENs));
			this._HOPDONG_HDVs = new EntitySet<HOPDONG_HDV>(new Action<HOPDONG_HDV>(this.attach_HOPDONG_HDVs), new Action<HOPDONG_HDV>(this.detach_HOPDONG_HDVs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_HDV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_HDV
		{
			get
			{
				return this._MA_HDV;
			}
			set
			{
				if ((this._MA_HDV != value))
				{
					this.OnMA_HDVChanging(value);
					this.SendPropertyChanging();
					this._MA_HDV = value;
					this.SendPropertyChanged("MA_HDV");
					this.OnMA_HDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_HDV", DbType="NVarChar(50)")]
		public string TEN_HDV
		{
			get
			{
				return this._TEN_HDV;
			}
			set
			{
				if ((this._TEN_HDV != value))
				{
					this.OnTEN_HDVChanging(value);
					this.SendPropertyChanging();
					this._TEN_HDV = value;
					this.SendPropertyChanged("TEN_HDV");
					this.OnTEN_HDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(5)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int")]
		public System.Nullable<int> SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HUONGDANVIEN_CHUYEN", Storage="_CHUYENs", ThisKey="MA_HDV", OtherKey="MA_HDV")]
		public EntitySet<CHUYEN> CHUYENs
		{
			get
			{
				return this._CHUYENs;
			}
			set
			{
				this._CHUYENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HUONGDANVIEN_HOPDONG_HDV", Storage="_HOPDONG_HDVs", ThisKey="MA_HDV", OtherKey="MA_HDV")]
		public EntitySet<HOPDONG_HDV> HOPDONG_HDVs
		{
			get
			{
				return this._HOPDONG_HDVs;
			}
			set
			{
				this._HOPDONG_HDVs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHUYENs(CHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.HUONGDANVIEN = this;
		}
		
		private void detach_CHUYENs(CHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.HUONGDANVIEN = null;
		}
		
		private void attach_HOPDONG_HDVs(HOPDONG_HDV entity)
		{
			this.SendPropertyChanging();
			entity.HUONGDANVIEN = this;
		}
		
		private void detach_HOPDONG_HDVs(HOPDONG_HDV entity)
		{
			this.SendPropertyChanging();
			entity.HUONGDANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOTRINH")]
	public partial class LOTRINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANOIDI;
		
		private string _MANOIDEN;
		
		private EntitySet<CHITIET_DDC> _CHITIET_DDCs;
		
		private EntitySet<LOTRINH_TOUR> _LOTRINH_TOURs;
		
		private EntityRef<NOIDEN> _NOIDEN;
		
		private EntityRef<NOIDI> _NOIDI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANOIDIChanging(string value);
    partial void OnMANOIDIChanged();
    partial void OnMANOIDENChanging(string value);
    partial void OnMANOIDENChanged();
    #endregion
		
		public LOTRINH()
		{
			this._CHITIET_DDCs = new EntitySet<CHITIET_DDC>(new Action<CHITIET_DDC>(this.attach_CHITIET_DDCs), new Action<CHITIET_DDC>(this.detach_CHITIET_DDCs));
			this._LOTRINH_TOURs = new EntitySet<LOTRINH_TOUR>(new Action<LOTRINH_TOUR>(this.attach_LOTRINH_TOURs), new Action<LOTRINH_TOUR>(this.detach_LOTRINH_TOURs));
			this._NOIDEN = default(EntityRef<NOIDEN>);
			this._NOIDI = default(EntityRef<NOIDI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANOIDI", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANOIDI
		{
			get
			{
				return this._MANOIDI;
			}
			set
			{
				if ((this._MANOIDI != value))
				{
					if (this._NOIDI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANOIDIChanging(value);
					this.SendPropertyChanging();
					this._MANOIDI = value;
					this.SendPropertyChanged("MANOIDI");
					this.OnMANOIDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANOIDEN", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANOIDEN
		{
			get
			{
				return this._MANOIDEN;
			}
			set
			{
				if ((this._MANOIDEN != value))
				{
					if (this._NOIDEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANOIDENChanging(value);
					this.SendPropertyChanging();
					this._MANOIDEN = value;
					this.SendPropertyChanged("MANOIDEN");
					this.OnMANOIDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOTRINH_CHITIET_DDC", Storage="_CHITIET_DDCs", ThisKey="MANOIDI,MANOIDEN", OtherKey="MANOIDI,MANOIDEN")]
		public EntitySet<CHITIET_DDC> CHITIET_DDCs
		{
			get
			{
				return this._CHITIET_DDCs;
			}
			set
			{
				this._CHITIET_DDCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOTRINH_LOTRINH_TOUR", Storage="_LOTRINH_TOURs", ThisKey="MANOIDI,MANOIDEN", OtherKey="MANOIDI,MANOIDEN")]
		public EntitySet<LOTRINH_TOUR> LOTRINH_TOURs
		{
			get
			{
				return this._LOTRINH_TOURs;
			}
			set
			{
				this._LOTRINH_TOURs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NOIDEN_LOTRINH", Storage="_NOIDEN", ThisKey="MANOIDEN", OtherKey="MANOIDEN", IsForeignKey=true)]
		public NOIDEN NOIDEN
		{
			get
			{
				return this._NOIDEN.Entity;
			}
			set
			{
				NOIDEN previousValue = this._NOIDEN.Entity;
				if (((previousValue != value) 
							|| (this._NOIDEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NOIDEN.Entity = null;
						previousValue.LOTRINHs.Remove(this);
					}
					this._NOIDEN.Entity = value;
					if ((value != null))
					{
						value.LOTRINHs.Add(this);
						this._MANOIDEN = value.MANOIDEN;
					}
					else
					{
						this._MANOIDEN = default(string);
					}
					this.SendPropertyChanged("NOIDEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NOIDI_LOTRINH", Storage="_NOIDI", ThisKey="MANOIDI", OtherKey="MANOIDI", IsForeignKey=true)]
		public NOIDI NOIDI
		{
			get
			{
				return this._NOIDI.Entity;
			}
			set
			{
				NOIDI previousValue = this._NOIDI.Entity;
				if (((previousValue != value) 
							|| (this._NOIDI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NOIDI.Entity = null;
						previousValue.LOTRINHs.Remove(this);
					}
					this._NOIDI.Entity = value;
					if ((value != null))
					{
						value.LOTRINHs.Add(this);
						this._MANOIDI = value.MANOIDI;
					}
					else
					{
						this._MANOIDI = default(string);
					}
					this.SendPropertyChanged("NOIDI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIET_DDCs(CHITIET_DDC entity)
		{
			this.SendPropertyChanging();
			entity.LOTRINH = this;
		}
		
		private void detach_CHITIET_DDCs(CHITIET_DDC entity)
		{
			this.SendPropertyChanging();
			entity.LOTRINH = null;
		}
		
		private void attach_LOTRINH_TOURs(LOTRINH_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.LOTRINH = this;
		}
		
		private void detach_LOTRINH_TOURs(LOTRINH_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.LOTRINH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOTRINH_TOUR")]
	public partial class LOTRINH_TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATOUR;
		
		private string _MANOIDI;
		
		private string _MANOIDEN;
		
		private System.Nullable<System.DateTime> _NGAYBATDAU;
		
		private System.Nullable<System.DateTime> _NGAYKETTHUC;
		
		private string _LOAI_PT;
		
		private string _LOAI_KS;
		
		private EntityRef<LOTRINH> _LOTRINH;
		
		private EntityRef<TOUR> _TOUR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATOURChanging(string value);
    partial void OnMATOURChanged();
    partial void OnMANOIDIChanging(string value);
    partial void OnMANOIDIChanged();
    partial void OnMANOIDENChanging(string value);
    partial void OnMANOIDENChanged();
    partial void OnNGAYBATDAUChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYBATDAUChanged();
    partial void OnNGAYKETTHUCChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYKETTHUCChanged();
    partial void OnLOAI_PTChanging(string value);
    partial void OnLOAI_PTChanged();
    partial void OnLOAI_KSChanging(string value);
    partial void OnLOAI_KSChanged();
    #endregion
		
		public LOTRINH_TOUR()
		{
			this._LOTRINH = default(EntityRef<LOTRINH>);
			this._TOUR = default(EntityRef<TOUR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATOUR", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATOUR
		{
			get
			{
				return this._MATOUR;
			}
			set
			{
				if ((this._MATOUR != value))
				{
					if (this._TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATOURChanging(value);
					this.SendPropertyChanging();
					this._MATOUR = value;
					this.SendPropertyChanged("MATOUR");
					this.OnMATOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANOIDI", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANOIDI
		{
			get
			{
				return this._MANOIDI;
			}
			set
			{
				if ((this._MANOIDI != value))
				{
					if (this._LOTRINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANOIDIChanging(value);
					this.SendPropertyChanging();
					this._MANOIDI = value;
					this.SendPropertyChanged("MANOIDI");
					this.OnMANOIDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANOIDEN", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANOIDEN
		{
			get
			{
				return this._MANOIDEN;
			}
			set
			{
				if ((this._MANOIDEN != value))
				{
					if (this._LOTRINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANOIDENChanging(value);
					this.SendPropertyChanging();
					this._MANOIDEN = value;
					this.SendPropertyChanged("MANOIDEN");
					this.OnMANOIDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYBATDAU", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYBATDAU
		{
			get
			{
				return this._NGAYBATDAU;
			}
			set
			{
				if ((this._NGAYBATDAU != value))
				{
					this.OnNGAYBATDAUChanging(value);
					this.SendPropertyChanging();
					this._NGAYBATDAU = value;
					this.SendPropertyChanged("NGAYBATDAU");
					this.OnNGAYBATDAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYKETTHUC", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYKETTHUC
		{
			get
			{
				return this._NGAYKETTHUC;
			}
			set
			{
				if ((this._NGAYKETTHUC != value))
				{
					this.OnNGAYKETTHUCChanging(value);
					this.SendPropertyChanging();
					this._NGAYKETTHUC = value;
					this.SendPropertyChanged("NGAYKETTHUC");
					this.OnNGAYKETTHUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAI_PT", DbType="VarChar(10)")]
		public string LOAI_PT
		{
			get
			{
				return this._LOAI_PT;
			}
			set
			{
				if ((this._LOAI_PT != value))
				{
					this.OnLOAI_PTChanging(value);
					this.SendPropertyChanging();
					this._LOAI_PT = value;
					this.SendPropertyChanged("LOAI_PT");
					this.OnLOAI_PTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAI_KS", DbType="VarChar(10)")]
		public string LOAI_KS
		{
			get
			{
				return this._LOAI_KS;
			}
			set
			{
				if ((this._LOAI_KS != value))
				{
					this.OnLOAI_KSChanging(value);
					this.SendPropertyChanging();
					this._LOAI_KS = value;
					this.SendPropertyChanged("LOAI_KS");
					this.OnLOAI_KSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOTRINH_LOTRINH_TOUR", Storage="_LOTRINH", ThisKey="MANOIDI,MANOIDEN", OtherKey="MANOIDI,MANOIDEN", IsForeignKey=true)]
		public LOTRINH LOTRINH
		{
			get
			{
				return this._LOTRINH.Entity;
			}
			set
			{
				LOTRINH previousValue = this._LOTRINH.Entity;
				if (((previousValue != value) 
							|| (this._LOTRINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOTRINH.Entity = null;
						previousValue.LOTRINH_TOURs.Remove(this);
					}
					this._LOTRINH.Entity = value;
					if ((value != null))
					{
						value.LOTRINH_TOURs.Add(this);
						this._MANOIDI = value.MANOIDI;
						this._MANOIDEN = value.MANOIDEN;
					}
					else
					{
						this._MANOIDI = default(string);
						this._MANOIDEN = default(string);
					}
					this.SendPropertyChanged("LOTRINH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_LOTRINH_TOUR", Storage="_TOUR", ThisKey="MATOUR", OtherKey="MATOUR", IsForeignKey=true)]
		public TOUR TOUR
		{
			get
			{
				return this._TOUR.Entity;
			}
			set
			{
				TOUR previousValue = this._TOUR.Entity;
				if (((previousValue != value) 
							|| (this._TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOUR.Entity = null;
						previousValue.LOTRINH_TOURs.Remove(this);
					}
					this._TOUR.Entity = value;
					if ((value != null))
					{
						value.LOTRINH_TOURs.Add(this);
						this._MATOUR = value.MATOUR;
					}
					else
					{
						this._MATOUR = default(string);
					}
					this.SendPropertyChanged("TOUR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOIDEN")]
	public partial class NOIDEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANOIDEN;
		
		private string _TENNOIDEN;
		
		private string _TP_NOIDEN;
		
		private EntitySet<LOTRINH> _LOTRINHs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANOIDENChanging(string value);
    partial void OnMANOIDENChanged();
    partial void OnTENNOIDENChanging(string value);
    partial void OnTENNOIDENChanged();
    partial void OnTP_NOIDENChanging(string value);
    partial void OnTP_NOIDENChanged();
    #endregion
		
		public NOIDEN()
		{
			this._LOTRINHs = new EntitySet<LOTRINH>(new Action<LOTRINH>(this.attach_LOTRINHs), new Action<LOTRINH>(this.detach_LOTRINHs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANOIDEN", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANOIDEN
		{
			get
			{
				return this._MANOIDEN;
			}
			set
			{
				if ((this._MANOIDEN != value))
				{
					this.OnMANOIDENChanging(value);
					this.SendPropertyChanging();
					this._MANOIDEN = value;
					this.SendPropertyChanged("MANOIDEN");
					this.OnMANOIDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNOIDEN", DbType="NVarChar(50)")]
		public string TENNOIDEN
		{
			get
			{
				return this._TENNOIDEN;
			}
			set
			{
				if ((this._TENNOIDEN != value))
				{
					this.OnTENNOIDENChanging(value);
					this.SendPropertyChanging();
					this._TENNOIDEN = value;
					this.SendPropertyChanged("TENNOIDEN");
					this.OnTENNOIDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TP_NOIDEN", DbType="NVarChar(50)")]
		public string TP_NOIDEN
		{
			get
			{
				return this._TP_NOIDEN;
			}
			set
			{
				if ((this._TP_NOIDEN != value))
				{
					this.OnTP_NOIDENChanging(value);
					this.SendPropertyChanging();
					this._TP_NOIDEN = value;
					this.SendPropertyChanged("TP_NOIDEN");
					this.OnTP_NOIDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NOIDEN_LOTRINH", Storage="_LOTRINHs", ThisKey="MANOIDEN", OtherKey="MANOIDEN")]
		public EntitySet<LOTRINH> LOTRINHs
		{
			get
			{
				return this._LOTRINHs;
			}
			set
			{
				this._LOTRINHs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LOTRINHs(LOTRINH entity)
		{
			this.SendPropertyChanging();
			entity.NOIDEN = this;
		}
		
		private void detach_LOTRINHs(LOTRINH entity)
		{
			this.SendPropertyChanging();
			entity.NOIDEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOIDI")]
	public partial class NOIDI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANOIDI;
		
		private string _TENNOIDI;
		
		private string _TP_NOIDI;
		
		private EntitySet<LOTRINH> _LOTRINHs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANOIDIChanging(string value);
    partial void OnMANOIDIChanged();
    partial void OnTENNOIDIChanging(string value);
    partial void OnTENNOIDIChanged();
    partial void OnTP_NOIDIChanging(string value);
    partial void OnTP_NOIDIChanged();
    #endregion
		
		public NOIDI()
		{
			this._LOTRINHs = new EntitySet<LOTRINH>(new Action<LOTRINH>(this.attach_LOTRINHs), new Action<LOTRINH>(this.detach_LOTRINHs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANOIDI", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANOIDI
		{
			get
			{
				return this._MANOIDI;
			}
			set
			{
				if ((this._MANOIDI != value))
				{
					this.OnMANOIDIChanging(value);
					this.SendPropertyChanging();
					this._MANOIDI = value;
					this.SendPropertyChanged("MANOIDI");
					this.OnMANOIDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNOIDI", DbType="NVarChar(50)")]
		public string TENNOIDI
		{
			get
			{
				return this._TENNOIDI;
			}
			set
			{
				if ((this._TENNOIDI != value))
				{
					this.OnTENNOIDIChanging(value);
					this.SendPropertyChanging();
					this._TENNOIDI = value;
					this.SendPropertyChanged("TENNOIDI");
					this.OnTENNOIDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TP_NOIDI", DbType="NVarChar(50)")]
		public string TP_NOIDI
		{
			get
			{
				return this._TP_NOIDI;
			}
			set
			{
				if ((this._TP_NOIDI != value))
				{
					this.OnTP_NOIDIChanging(value);
					this.SendPropertyChanging();
					this._TP_NOIDI = value;
					this.SendPropertyChanged("TP_NOIDI");
					this.OnTP_NOIDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NOIDI_LOTRINH", Storage="_LOTRINHs", ThisKey="MANOIDI", OtherKey="MANOIDI")]
		public EntitySet<LOTRINH> LOTRINHs
		{
			get
			{
				return this._LOTRINHs;
			}
			set
			{
				this._LOTRINHs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LOTRINHs(LOTRINH entity)
		{
			this.SendPropertyChanging();
			entity.NOIDI = this;
		}
		
		private void detach_LOTRINHs(LOTRINH entity)
		{
			this.SendPropertyChanging();
			entity.NOIDI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUDANGKI")]
	public partial class PHIEUDANGKI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPHIEU;
		
		private string _NOIDANGKI;
		
		private System.Nullable<System.DateTime> _NGAYDK;
		
		private string _TENKHACHDK;
		
		private System.Nullable<int> _SONGUOIDI;
		
		private System.Nullable<int> _SDT;
		
		private EntitySet<CHUYEN> _CHUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUChanging(string value);
    partial void OnMAPHIEUChanged();
    partial void OnNOIDANGKIChanging(string value);
    partial void OnNOIDANGKIChanged();
    partial void OnNGAYDKChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYDKChanged();
    partial void OnTENKHACHDKChanging(string value);
    partial void OnTENKHACHDKChanged();
    partial void OnSONGUOIDIChanging(System.Nullable<int> value);
    partial void OnSONGUOIDIChanged();
    partial void OnSDTChanging(System.Nullable<int> value);
    partial void OnSDTChanged();
    #endregion
		
		public PHIEUDANGKI()
		{
			this._CHUYENs = new EntitySet<CHUYEN>(new Action<CHUYEN>(this.attach_CHUYENs), new Action<CHUYEN>(this.detach_CHUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEU", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPHIEU
		{
			get
			{
				return this._MAPHIEU;
			}
			set
			{
				if ((this._MAPHIEU != value))
				{
					this.OnMAPHIEUChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEU = value;
					this.SendPropertyChanged("MAPHIEU");
					this.OnMAPHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDANGKI", DbType="NVarChar(50)")]
		public string NOIDANGKI
		{
			get
			{
				return this._NOIDANGKI;
			}
			set
			{
				if ((this._NOIDANGKI != value))
				{
					this.OnNOIDANGKIChanging(value);
					this.SendPropertyChanging();
					this._NOIDANGKI = value;
					this.SendPropertyChanged("NOIDANGKI");
					this.OnNOIDANGKIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDK", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYDK
		{
			get
			{
				return this._NGAYDK;
			}
			set
			{
				if ((this._NGAYDK != value))
				{
					this.OnNGAYDKChanging(value);
					this.SendPropertyChanging();
					this._NGAYDK = value;
					this.SendPropertyChanged("NGAYDK");
					this.OnNGAYDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKHACHDK", DbType="NVarChar(50)")]
		public string TENKHACHDK
		{
			get
			{
				return this._TENKHACHDK;
			}
			set
			{
				if ((this._TENKHACHDK != value))
				{
					this.OnTENKHACHDKChanging(value);
					this.SendPropertyChanging();
					this._TENKHACHDK = value;
					this.SendPropertyChanged("TENKHACHDK");
					this.OnTENKHACHDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONGUOIDI", DbType="Int")]
		public System.Nullable<int> SONGUOIDI
		{
			get
			{
				return this._SONGUOIDI;
			}
			set
			{
				if ((this._SONGUOIDI != value))
				{
					this.OnSONGUOIDIChanging(value);
					this.SendPropertyChanging();
					this._SONGUOIDI = value;
					this.SendPropertyChanged("SONGUOIDI");
					this.OnSONGUOIDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int")]
		public System.Nullable<int> SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDANGKI_CHUYEN", Storage="_CHUYENs", ThisKey="MAPHIEU", OtherKey="MAPHIEU")]
		public EntitySet<CHUYEN> CHUYENs
		{
			get
			{
				return this._CHUYENs;
			}
			set
			{
				this._CHUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHUYENs(CHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDANGKI = this;
		}
		
		private void detach_CHUYENs(CHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDANGKI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TOUR")]
	public partial class TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATOUR;
		
		private string _TENTOUR;
		
		private System.Nullable<int> _SONGAY;
		
		private System.Nullable<int> _SODEM;
		
		private System.Nullable<decimal> _DONGIA;
		
		private EntitySet<CHUYEN> _CHUYENs;
		
		private EntitySet<CT_DIEMTHAMQUAN> _CT_DIEMTHAMQUANs;
		
		private EntitySet<HOPDONG> _HOPDONGs;
		
		private EntitySet<LOTRINH_TOUR> _LOTRINH_TOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATOURChanging(string value);
    partial void OnMATOURChanged();
    partial void OnTENTOURChanging(string value);
    partial void OnTENTOURChanged();
    partial void OnSONGAYChanging(System.Nullable<int> value);
    partial void OnSONGAYChanged();
    partial void OnSODEMChanging(System.Nullable<int> value);
    partial void OnSODEMChanged();
    partial void OnDONGIAChanging(System.Nullable<decimal> value);
    partial void OnDONGIAChanged();
    #endregion
		
		public TOUR()
		{
			this._CHUYENs = new EntitySet<CHUYEN>(new Action<CHUYEN>(this.attach_CHUYENs), new Action<CHUYEN>(this.detach_CHUYENs));
			this._CT_DIEMTHAMQUANs = new EntitySet<CT_DIEMTHAMQUAN>(new Action<CT_DIEMTHAMQUAN>(this.attach_CT_DIEMTHAMQUANs), new Action<CT_DIEMTHAMQUAN>(this.detach_CT_DIEMTHAMQUANs));
			this._HOPDONGs = new EntitySet<HOPDONG>(new Action<HOPDONG>(this.attach_HOPDONGs), new Action<HOPDONG>(this.detach_HOPDONGs));
			this._LOTRINH_TOURs = new EntitySet<LOTRINH_TOUR>(new Action<LOTRINH_TOUR>(this.attach_LOTRINH_TOURs), new Action<LOTRINH_TOUR>(this.detach_LOTRINH_TOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATOUR", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATOUR
		{
			get
			{
				return this._MATOUR;
			}
			set
			{
				if ((this._MATOUR != value))
				{
					this.OnMATOURChanging(value);
					this.SendPropertyChanging();
					this._MATOUR = value;
					this.SendPropertyChanged("MATOUR");
					this.OnMATOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTOUR", DbType="NVarChar(50)")]
		public string TENTOUR
		{
			get
			{
				return this._TENTOUR;
			}
			set
			{
				if ((this._TENTOUR != value))
				{
					this.OnTENTOURChanging(value);
					this.SendPropertyChanging();
					this._TENTOUR = value;
					this.SendPropertyChanged("TENTOUR");
					this.OnTENTOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONGAY", DbType="Int")]
		public System.Nullable<int> SONGAY
		{
			get
			{
				return this._SONGAY;
			}
			set
			{
				if ((this._SONGAY != value))
				{
					this.OnSONGAYChanging(value);
					this.SendPropertyChanging();
					this._SONGAY = value;
					this.SendPropertyChanged("SONGAY");
					this.OnSONGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODEM", DbType="Int")]
		public System.Nullable<int> SODEM
		{
			get
			{
				return this._SODEM;
			}
			set
			{
				if ((this._SODEM != value))
				{
					this.OnSODEMChanging(value);
					this.SendPropertyChanging();
					this._SODEM = value;
					this.SendPropertyChanged("SODEM");
					this.OnSODEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_CHUYEN", Storage="_CHUYENs", ThisKey="MATOUR", OtherKey="MATOUR")]
		public EntitySet<CHUYEN> CHUYENs
		{
			get
			{
				return this._CHUYENs;
			}
			set
			{
				this._CHUYENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_CT_DIEMTHAMQUAN", Storage="_CT_DIEMTHAMQUANs", ThisKey="MATOUR", OtherKey="MATOUR")]
		public EntitySet<CT_DIEMTHAMQUAN> CT_DIEMTHAMQUANs
		{
			get
			{
				return this._CT_DIEMTHAMQUANs;
			}
			set
			{
				this._CT_DIEMTHAMQUANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_HOPDONG", Storage="_HOPDONGs", ThisKey="MATOUR", OtherKey="MATOUR")]
		public EntitySet<HOPDONG> HOPDONGs
		{
			get
			{
				return this._HOPDONGs;
			}
			set
			{
				this._HOPDONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_LOTRINH_TOUR", Storage="_LOTRINH_TOURs", ThisKey="MATOUR", OtherKey="MATOUR")]
		public EntitySet<LOTRINH_TOUR> LOTRINH_TOURs
		{
			get
			{
				return this._LOTRINH_TOURs;
			}
			set
			{
				this._LOTRINH_TOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHUYENs(CHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = this;
		}
		
		private void detach_CHUYENs(CHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = null;
		}
		
		private void attach_CT_DIEMTHAMQUANs(CT_DIEMTHAMQUAN entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = this;
		}
		
		private void detach_CT_DIEMTHAMQUANs(CT_DIEMTHAMQUAN entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = null;
		}
		
		private void attach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = this;
		}
		
		private void detach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = null;
		}
		
		private void attach_LOTRINH_TOURs(LOTRINH_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = this;
		}
		
		private void detach_LOTRINH_TOURs(LOTRINH_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = null;
		}
	}
}
#pragma warning restore 1591
